all:
	gcc -Wall -c main.c
	gcc -Wall -c minK/auxiliaryFunctions.c
	gcc -Wall -c minK/functions.c
	gcc -Wall -c minK/heapSort.c
	gcc -Wall -c minK/vectorFunctions.c
	gcc -Wall -c minK/priorityQueue.c
	gcc -Wall -c minK/quickSort.c
	gcc -Wall -o main *.o
	./main
	del *.o
	del main.exe
